### ISSUE TITLE
Add a feature to supply initial value for self CD registration

### ISSUE THREAD

**Issue by ocadaruma** [line/decaton#22]
- When we create property file using `CentralDogmaPropertySupplier#register`, the file consists of default values.
- If we know appropriate value for a property at the beginning, this will require extra step to configure it
  * `CentralDogmaPropertySupplier#register`
  * update value on CentralDogma

**Comment by fallaciesk** [comment]
Instead of letting `CentralDogmaPropertySupplier#register` create a JSON if missing with custom values, can we change it to NOT create a JSON at all ?

Say we construct subscription with multiple suppliers, and want to get different properties from different suppliers:
```
suppliers = [
    supplier1,  // property1
    supplier2,  //            property2            property4
    supplier3,  //                       property3
]
```

If we use `CentralDogmaPropertySupplier` and it automatically creates a JSON of all properties, with no matter default or custom values, then it shadows all suppliers after  it:

```
suppliers = [
    cd-supplier, // property1 default2 custom3 default4
    supplier2,   // (won't be used)
    supplier3,   // (won't be used)
]
```

To prevent this, we have to disable write permission at CD, and manually create a JSON with only wanted properties.
```
// JSON at CD
{
    "property1": "abc"
}

// code
suppliers = [cd-supplier, supplier2, supplier3]
```

If we change it to NOT automatically create JSON at all, then we can do like
```
suppliers = [
    cd-supplier,      // property1 
    supplier2,        //           property2
    default-supplier, // (all other properties with custom values)
]
```

Suppliers layered, and all missing values provided by a default supplier. And `supplier2` actually acts as the "custom values supplier".

**Comment by lazmond3** [comment]
I’ll try this one.

**Comment by kawamuray** [comment]
Solved by https://github.com/line/decaton/pull/134
